### ISSUE TITLE
Uncaught exception when upgrading past v2.5.5-ls12 

### ISSUE THREAD

**Issue by lenaxia** [linuxserver/docker-tautulli#104]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Tautulli should start correctly

## Current Behavior
container fails to start with an uncaught exception

## Steps to Reproduce
1. docker-compose up
2. Observe failure
3. revert back to linuxserver/tautulli:v2.5.5-ls12 and failure goes away
4. Backups of my database can be provided to aid in reproduction

## Environment
**OS:** Ubuntu 20.04 LTS
**CPU architecture:** x86_64
**How docker service was installed:**
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2"
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TAUTULLI_DOCKER=True
    volumes:
      - /mnt/docker/tautulli:/config
      - "/mnt/plexdata/Library/Application Support/Plex Media Server/Logs/:/logs:ro"
    ports:
      - 8181:8181
    restart: unless-stopped
    networks:
      - medianet
      - t2_proxy
```

## Docker logs

```
2021-05-14T17:58:22.803999169Z usermod: no changes
2021-05-14T17:58:22.804085318Z
2021-05-14T17:58:22.804115629Z -------------------------------------
2021-05-14T17:58:22.804132716Z           _         ()
2021-05-14T17:58:22.804143479Z          | |  ___   _    __
2021-05-14T17:58:22.804153694Z          | | / __| | |  /  \
2021-05-14T17:58:22.804164143Z          | | \__ \ | | | () |
2021-05-14T17:58:22.804174826Z          |_| |___/ |_|  \__/
2021-05-14T17:58:22.804185133Z
2021-05-14T17:58:22.804194856Z
2021-05-14T17:58:22.804204587Z Brought to you by linuxserver.io
2021-05-14T17:58:22.804214664Z -------------------------------------
2021-05-14T17:58:22.804225060Z
2021-05-14T17:58:22.804234924Z To support the app dev(s) visit:
2021-05-14T17:58:22.806182852Z Tautulli: https://tautulli.com/#donate
2021-05-14T17:58:22.806671720Z
2021-05-14T17:58:22.806715693Z To support LSIO projects visit:
2021-05-14T17:58:22.806731080Z https://www.linuxserver.io/donate/
2021-05-14T17:58:22.806743496Z -------------------------------------
2021-05-14T17:58:22.806755387Z GID/UID
2021-05-14T17:58:22.806770971Z -------------------------------------
2021-05-14T17:58:22.816450568Z
2021-05-14T17:58:22.816493763Z User uid:    1000
2021-05-14T17:58:22.816506125Z User gid:    1000
2021-05-14T17:58:22.816515027Z -------------------------------------
2021-05-14T17:58:22.816523203Z
2021-05-14T17:58:22.825753321Z [cont-init.d] 10-adduser: exited 0.
2021-05-14T17:58:22.827188173Z [cont-init.d] 30-config: executing...
2021-05-14T17:58:22.870416895Z [cont-init.d] 30-config: exited 0.
2021-05-14T17:58:22.871678158Z [cont-init.d] 99-custom-files: executing...
2021-05-14T17:58:22.876937693Z [custom-init] no custom files found exiting...
2021-05-14T17:58:22.877304652Z [cont-init.d] 99-custom-files: exited 0.
2021-05-14T17:58:22.877858253Z [cont-init.d] done.
2021-05-14T17:58:22.878448784Z [services.d] starting services
2021-05-14T17:58:22.884597218Z [services.d] done.
2021-05-14T17:58:23.830643893Z 2021-05-14 10:58:23 - INFO :: MainThread : Starting Tautulli v2.6.10
2021-05-14T17:58:23.831140302Z 2021-05-14 10:58:23 - INFO :: MainThread : [Docker] Linux 4.15.0-140-generic (#144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021)
2021-05-14T17:58:23.831610126Z 2021-05-14 10:58:23 - INFO :: MainThread : America/Los_Angeles (UTC-0700)
2021-05-14T17:58:23.832081032Z 2021-05-14 10:58:23 - INFO :: MainThread : Python 3.8.8 (default, Mar 15 2021, 13:10:14) [GCC 10.2.1 20201203]
2021-05-14T17:58:23.832489514Z 2021-05-14 10:58:23 - INFO :: MainThread : Program Dir: /app/tautulli
2021-05-14T17:58:23.832936001Z 2021-05-14 10:58:23 - INFO :: MainThread : Config File: /config/config.ini
2021-05-14T17:58:23.833401607Z 2021-05-14 10:58:23 - INFO :: MainThread : Database File: /config/tautulli.db
2021-05-14T17:58:23.834044012Z 2021-05-14 10:58:23 - INFO :: MainThread : Checking if the database upgrades are required...
2021-05-14T17:58:23.848418488Z 2021-05-14 10:58:23 - DEBUG :: MainThread : Altering database. Updating database table library_sections.
2021-05-14T17:58:23.849360085Z 2021-05-14 10:58:23 - DEBUG :: MainThread : Altering database. Updating database table notifiers.
2021-05-14T17:58:23.870754667Z 2021-05-14 10:58:23 - ERROR :: MainThread : Can't connect to the database: UNIQUE constraint failed: cloudinary_lookup.img_hash
2021-05-14T17:58:23.872174842Z 2021-05-14 10:58:23 - INFO :: MainThread : Checking if configuration upgrades are required...
2021-05-14T17:58:23.876285630Z 2021-05-14 10:58:23 - DEBUG :: MainThread : Using cached GitHub version data
2021-05-14T17:58:23.877318102Z 2021-05-14 10:58:23 - DEBUG :: MainThread : Latest version is 39ad3f9047fb3f8ed7b18b1584b079a70280d37b
2021-05-14T17:58:23.877990917Z 2021-05-14 10:58:23 - DEBUG :: MainThread : Using cached GitHub commits data
2021-05-14T17:58:23.878574319Z 2021-05-14 10:58:23 - DEBUG :: MainThread : In total, 0 commits behind
2021-05-14T17:58:23.878956908Z 2021-05-14 10:58:23 - INFO :: MainThread : Tautulli is up to date
2021-05-14T17:58:23.880287179Z 2021-05-14 10:58:23 - INFO :: Thread-1 : Tautulli PlexTV :: Requesting resources for server...
2021-05-14T17:58:23.883131587Z 2021-05-14 10:58:23 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
2021-05-14T17:58:23.885624535Z 2021-05-14 10:58:23 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: on_error
2021-05-14T17:58:23.892867124Z 2021-05-14 10:58:23 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
2021-05-14T17:58:23.892882164Z   File "/app/tautulli/Tautulli.py", line 324, in <module>
2021-05-14T17:58:23.892886161Z     main()
2021-05-14T17:58:23.892888640Z   File "/app/tautulli/Tautulli.py", line 237, in main
2021-05-14T17:58:23.892891243Z     plexpy.start()
2021-05-14T17:58:23.892902328Z   File "/app/tautulli/plexpy/__init__.py", line 550, in start
2021-05-14T17:58:23.892905000Z     notifiers.check_browser_enabled()
2021-05-14T17:58:23.892907399Z   File "/app/tautulli/plexpy/notifiers.py", line 3856, in check_browser_enabled
2021-05-14T17:58:23.892909866Z     for n in get_notifiers():
2021-05-14T17:58:23.892912123Z   File "/app/tautulli/plexpy/notifiers.py", line 457, in get_notifiers
2021-05-14T17:58:23.892914538Z     result = db.select('SELECT id, agent_id, agent_name, agent_label, friendly_name, %s FROM notifiers %s'
2021-05-14T17:58:23.892916956Z   File "/app/tautulli/plexpy/database.py", line 427, in select
2021-05-14T17:58:23.892920016Z     sql_results = self.action(query, args).fetchall()
2021-05-14T17:58:23.892923617Z   File "/app/tautulli/plexpy/database.py", line 405, in action
2021-05-14T17:58:23.892927280Z     sql_result = c.execute(query, args)
2021-05-14T17:58:23.892930897Z sqlite3.OperationalError: no such column: on_error
2021-05-14T17:58:23.892933272Z
2021-05-14T17:58:23.895309237Z Traceback (most recent call last):
2021-05-14T17:58:23.895322421Z   File "/app/tautulli/Tautulli.py", line 324, in <module>
2021-05-14T17:58:23.895327593Z     main()
2021-05-14T17:58:23.895331103Z   File "/app/tautulli/Tautulli.py", line 237, in main
2021-05-14T17:58:23.895334668Z     plexpy.start()
2021-05-14T17:58:23.895338196Z   File "/app/tautulli/plexpy/__init__.py", line 550, in start
2021-05-14T17:58:23.895342255Z     notifiers.check_browser_enabled()
2021-05-14T17:58:23.895345914Z   File "/app/tautulli/plexpy/notifiers.py", line 3856, in check_browser_enabled
2021-05-14T17:58:23.895350110Z     for n in get_notifiers():
2021-05-14T17:58:23.895352540Z   File "/app/tautulli/plexpy/notifiers.py", line 457, in get_notifiers
2021-05-14T17:58:23.895354877Z     result = db.select('SELECT id, agent_id, agent_name, agent_label, friendly_name, %s FROM notifiers %s'
2021-05-14T17:58:23.895357364Z   File "/app/tautulli/plexpy/database.py", line 427, in select
2021-05-14T17:58:23.895359997Z     sql_results = self.action(query, args).fetchall()
2021-05-14T17:58:23.895362297Z   File "/app/tautulli/plexpy/database.py", line 405, in action
2021-05-14T17:58:23.895364614Z     sql_result = c.execute(query, args)
2021-05-14T17:58:23.895366870Z sqlite3.OperationalError: no such column: on_error
2021-05-14T17:58:25.004720745Z 2021-05-14 10:58:25 - INFO :: Thread-1 : Tautulli Config :: Writing configuration to file
2021-05-14T17:58:25.016777594Z 2021-05-14 10:58:25 - INFO :: Thread-1 : Tautulli PlexTV :: Using user-defined URL.
2021-05-14T17:58:25.017872090Z 2021-05-14 10:58:25 - INFO :: Thread-1 : Tautulli PlexTV :: Selected server: HoshinoRuri (http://hoshinoruri:32400) (Linux - Version 1.22.3.4523-d0ce30438)
2021-05-14T17:58:25.025532093Z 2021-05-14 10:58:25 - INFO :: Thread-1 : Tautulli Config :: Writing configuration to file
2021-05-14T17:58:25.039634133Z 2021-05-14 10:58:25 - DEBUG :: Thread-1 : Tautulli Monitor :: Checking for active streams.
2021-05-14T17:58:25.040671186Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Tautulli WebSocket :: Opening websocket.
2021-05-14T17:58:25.041357477Z 2021-05-14 10:58:25 - INFO :: Thread-1 : Tautulli Users :: Requesting users list refresh...
2021-05-14T17:58:25.044463000Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Tautulli WebSocket :: Ready
2021-05-14T17:58:25.045264994Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Scheduled background task: Check GitHub for updates
2021-05-14T17:58:25.045925204Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Scheduled background task: Optimize Tautulli database
2021-05-14T17:58:25.046588775Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Scheduled background task: Backup Tautulli database
2021-05-14T17:58:25.047198329Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Scheduled background task: Backup Tautulli config
2021-05-14T17:58:25.047932374Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Scheduled background task: Refresh Plex server URLs
2021-05-14T17:58:25.048533866Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Scheduled background task: Refresh users list
2021-05-14T17:58:25.049117943Z 2021-05-14 10:58:25 - INFO :: Thread-4 : Scheduled background task: Refresh libraries list
2021-05-14T17:58:26.565139407Z 2021-05-14 10:58:26 - INFO :: Thread-1 : Tautulli Users :: Users list refreshed.
2021-05-14T17:58:26.565881774Z 2021-05-14 10:58:26 - INFO :: Thread-1 : Tautulli Libraries :: Requesting libraries list refresh...
2021-05-14T17:58:27.065225648Z 2021-05-14 10:58:27 - DEBUG :: Thread-1 : Tautulli Pmsconnect :: No library data.
2021-05-14T17:58:27.069014216Z 2021-05-14 10:58:27 - DEBUG :: Thread-1 : Tautulli Pmsconnect :: No library data.
2021-05-14T17:58:27.072767199Z 2021-05-14 10:58:27 - DEBUG :: Thread-1 : Tautulli Pmsconnect :: No library data.
2021-05-14T17:58:27.113753973Z 2021-05-14 10:58:27 - INFO :: Thread-1 : Tautulli Config :: Writing configuration to file
2021-05-14T17:58:27.121285540Z 2021-05-14 10:58:27 - INFO :: Thread-1 : Tautulli Libraries :: Libraries list refreshed.
```

**Comment by thespad** [comment]
This looks like the result of a failed database migration during a previous upgrade that's left it in an inconsistent state. You can try restoring from an older backup if you have one but this isn't a container issue per se so you're probably better off seeking support directly from Tautulli https://github.com/Tautulli/Tautulli
