### ISSUE TITLE
[BUG] Docker-Tautulli won't start on QNAP

### ISSUE THREAD

**Issue by yrubdarb** [linuxserver/docker-tautulli#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):

### Expected Behavior

To start up as normal

### Steps To Reproduce

Started up as normal 
but is missing as module as in logs below  

### Environment

```markdown
- OS: QNAP QTS 5.0.1.2376 
- Latest imaged pulled : was working before
```

### CPU architecture

x86-64

### Docker creation

```bash
{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/init"
        ],
        "Env": [
            "HOME=/root",
            "LSIO_FIRST_PARTY=true",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "PGID=0",
            "PS1=$(whoami)@$(hostname):$(pwd)\\$",
            "PUID=0",
            "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
            "S6_STAGE2_HOOK=/docker-mods",
            "S6_VERBOSITY=1",
            "TAUTULLI_DOCKER=True",
            "TERM=xterm",
            "TZ=Australia/Darwin",
            "VIRTUAL_ENV=/lsiopy"
        ],
        "ExposedPorts": {
            "8181/tcp": {}
        },
        "Hostname": "venus",
        "Image": "linuxserver/tautulli:latest",
        "Labels": {
            "build_version": "Linuxserver.io version:- v2.10.2-ls42 Build-date:- 2022-07-15T06:41:31+02:00",
            "com.qnap.qcs.gpu": "False",
            "com.qnap.qcs.network.mode": "host",
            "maintainer": "nemchik,thelamer",
            "org.opencontainers.image.authors": "linuxserver.io",
            "org.opencontainers.image.created": "2022-07-15T06:41:31+02:00",
            "org.opencontainers.image.description": "[Tautulli](http://tautulli.com) is a python based web application for monitoring, analytics and notifications for Plex Media Server.",
            "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-tautulli",
            "org.opencontainers.image.licenses": "GPL-3.0-only",
            "org.opencontainers.image.ref.name": "af2232606b16584508f686bd02fb118f42d7fc78",
            "org.opencontainers.image.revision": "af2232606b16584508f686bd02fb118f42d7fc78",
            "org.opencontainers.image.source": "https://github.com/linuxserver/docker-tautulli",
            "org.opencontainers.image.title": "Tautulli",
            "org.opencontainers.image.url": "https://github.com/linuxserver/docker-tautulli/packages",
            "org.opencontainers.image.vendor": "linuxserver.io",
            "org.opencontainers.image.version": "v2.10.2-ls42"
        },
        "OnBuild": null,
        "OpenStdin": true,
        "StdinOnce": false,
        "Tty": true,
        "User": "",
        "Volumes": {
            "/config": {}
        },
        "WorkingDir": "/"
    },
    "Created": "2023-05-28T02:37:09.286965324Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/468637e9518e91812ea71a47b172b367b2e9e9a4381df88ff78ec94372108088-init/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/ece17ec087c1863012776e219357d4f6a8d78113e848ba580a8105831c9bf9b3/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/1d9daa3e3aef08c0addfb791d9eabf9905585d54427fc7d6bd836a11284160f2/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/cccd1a5cc40d5a7a80f9d8ed123ad497fae659b1a142b0eb735b5d9886199ac9/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/bd377e5365d2740c7bb709c6ca80c6d2fda00dd23b6c07af93c963c13ca696f3/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/f5ce9164e4342b75a711eda089da3609d97e806da304b885329631b319f7c369/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/cbfc99a02cbcb3521d5503de2dad726e4ea94ec00786124ea17cf7b19373807f/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/d34530a4e368f3dd36b56a8240b9d79ddf7c4cea224182f0a1a63112731e516e/diff",
            "MergedDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/468637e9518e91812ea71a47b172b367b2e9e9a4381df88ff78ec94372108088/merged",
            "UpperDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/468637e9518e91812ea71a47b172b367b2e9e9a4381df88ff78ec94372108088/diff",
            "WorkDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/468637e9518e91812ea71a47b172b367b2e9e9a4381df88ff78ec94372108088/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/share/Containers/mounts/tautulli:/config"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 100000,
        "CpuQuota": -1,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [],
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {
                "max-file": "10",
                "max-size": "10m"
            },
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "host",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": true,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": [
            {
                "Hard": 65535,
                "Name": "nofile",
                "Soft": 65535
            }
        ],
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": []
    },
    "HostnamePath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/bb8807c258fa19fc3676c0d298e57a8c8059768c7dbca43cabc7ed71d6e4fa67/hostname",
    "HostsPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/bb8807c258fa19fc3676c0d298e57a8c8059768c7dbca43cabc7ed71d6e4fa67/hosts",
    "Id": "bb8807c258fa19fc3676c0d298e57a8c8059768c7dbca43cabc7ed71d6e4fa67",
    "Image": "sha256:bba358e3f4a064faef8e5c87f8b9b9df7919e0c517d7f7af863aec1f886b7ff7",
    "LogPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/bb8807c258fa19fc3676c0d298e57a8c8059768c7dbca43cabc7ed71d6e4fa67/bb8807c258fa19fc3676c0d298e57a8c8059768c7dbca43cabc7ed71d6e4fa67-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/config",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/share/Containers/mounts/tautulli",
            "Type": "bind"
        }
    ],
    "Name": "/tautulli-1",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "host": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "7a842d47a40df297fc3f292380cb0e98caee869ce7096d18dbbc2f1a9c3e55f3",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "c469e1dd489e587ab38aba8aa7bbf6aeaffdd7c00dc4248f7bc4a85f07e7bd64"
            }
        },
        "Ports": {},
        "SandboxID": "8687e9c9fc07c882033672f42b7983d04c6428418f2abdb9a45965560d736dbd",
        "SandboxKey": "/var/run/docker/netns/default",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 89,
            "ResourceId": "bb8807c258fa19fc3676c0d298e57a8c8059768c7dbca43cabc7ed71d6e4fa67",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/bb8807c258fa19fc3676c0d298e57a8c8059768c7dbca43cabc7ed71d6e4fa67/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 820,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2023-05-28T02:37:09.734712826Z",
        "Status": "running"
    }
}
```

### Container logs

```bash
[~] # docker logs linuxserver.io
Error: No such container: linuxserver.io
[~] # docker logs tautulli-1     
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Tautulli: https://tautulli.com/#donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

[custom-init] No custom files found, skipping...
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
```

**Comment by j0nnymoe** [comment]
How can we reproduce this if you haven't provided details on how you've deployed it?

**Comment by yrubdarb** [comment]
It is running in container station on a QNAP I also have Portainer running as a container Tautulli is displaying A[ new release (v2.12.4)]( of Tautulli is available! I did a recreate in portainer pulling the latest image and once restarted  I get the errors that I posted above. I reverted to the old image that was still on the NAS and it is now working .again.

**Comment by Roxedus** [comment]
It's a portainer issue. https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by yrubdarb** [comment]
Thanks, Did a manual update and it is working..
Thanks you for your help

**Comment by MilesTEG1** [comment]
Hello,
For the record, I've got the same problem/error on my Synology NAS, and also with Portainer.
I stop the stack (stack with Plex Media Server):
![image](https://github.com/linuxserver/docker-tautulli/assets/29298312/6fe540af-6f7d-4425-87b5-17312a1b1fc9)
Then, "Pull and redeploy":
![image](https://github.com/linuxserver/docker-tautulli/assets/29298312/9ac8a475-075a-4c02-889b-047bb4f674ff)
And Tautulli was working fine again.

**Comment by cheerfulnut** [comment]
> Hello, For the record, I've got the same problem/error on my Synology NAS, and also with Portainer. I stop the stack (stack with Plex Media Server): ![image](https://user-images.githubusercontent.com/29298312/241560652-6fe540af-6f7d-4425-87b5-17312a1b1fc9.png) Then, "Pull and redeploy": ![image](https://user-images.githubusercontent.com/29298312/241560686-9ac8a475-075a-4c02-889b-047bb4f674ff.png) And Tautulli was working fine again.

Just wanted to say thank you for posting this - fixed the same issue I had on portainer installed on ubuntu.  I didn't have the option to "pull and redeploy", but stopping and starting the stack fixed the issue.
