### ISSUE TITLE
[BUG] AST constructor issue with Python 3.11

### ISSUE THREAD

**Issue by suineg** [linuxserver/docker-tautulli#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WebUI :: Mako template render error: (SystemError) AST constructor recursion depth mismatch (before=150, after=145) errors popping up and ruining the web interface. 

Known issue according to the Tautulli developer SwiftPanda

The functionality of the application is unaffected by this bug for the most part. A web interface glitching out every so often can be quite annoying but the service is still working as expected.

### Expected Behavior

No errors and clean interface.

### Steps To Reproduce

Load up the web interface and on a reload it can randomly have an issue that generates the error and cause a dump into the interface. Reloading can fix it but sometimes it takes a few. 

https://www.reddit.com/r/Tautulli/comments/1042t13/error_syntaxexception_systemerror_ast_constructor/ this is where the dev said that downgrading to python 3.10 will fix it. 

https://github.com/linuxserver/docker-tautulli/blob/master/package_versions.txt 
python                         3.11.3

I am not great with python so I don't know if some of the other packages tie into 3.11 that will need to be downgraded as well.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: Docker Compose
```

### CPU architecture

x86-64

### Docker creation

```bash
tautulli:
  image: lscr.io/linuxserver/tautulli
  container_name: tautulli
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
#  ports:
#    - 8181:8181
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.tautulli-rtr.entrypoints=websecure"
    - "traefik.http.routers.tautulli-rtr.rule=Host(`plexpy.kinkycoeds.gov`)"
    - "traefik.http.routers.tautulli-rtr.tls=true"
    - "traefik.http.routers.tautulli-rtr.middlewares=chain-no-auth@file"
    - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
    - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
  volumes:
    - /opt/plexpy:/config
    - /opt/plex/Library:/logs:ro
  restart: unless-stopped
```

### Container logs

```bash
tautulli  | 2023-06-09T17:08:43.159618217Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_play'.
tautulli  | 2023-06-09T17:08:43.162599383Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Checking global notification conditions.
tautulli  | 2023-06-09T17:08:43.165635689Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Global notification conditions evaluated to 'True'.
tautulli  | 2023-06-09T17:08:43.338706165Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Checking custom notification conditions for notifier_id 8.
tautulli  | 2023-06-09T17:08:43.342996856Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: {1} user | is not | 'ly********8' or 'ha********8' > 'Jo********3' > True
tautulli  | 2023-06-09T17:08:43.347281666Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: {2} video_decision | is | 'transcode' > 'direct play' > False
tautulli  | 2023-06-09T17:08:43.350626409Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Condition logic [blank]: {1} and {2} > False
tautulli  | 2023-06-09T17:08:43.353728625Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Custom conditions evaluated to 'False'. Conditions: [True, False].
tautulli  | 2023-06-09T17:08:43.356591532Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Custom notification conditions not satisfied, skipping notifier_id 8.
tautulli  | 2023-06-09T17:08:43.361186450Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_concurrent'.
tautulli  | 2023-06-09T17:08:43.363241920Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Checking global notification conditions.
tautulli  | 2023-06-09T17:08:43.430533294Z 2023-06-09 13:08:43 - DEBUG :: Thread-2 (process_queue) : Tautulli NotificationHandler :: Global notification conditions evaluated to 'False'.
tautulli  | 2023-06-09T17:08:45.081918825Z 2023-06-09 13:08:45 - DEBUG :: ThreadPoolExecutor-0_1 : Tautulli ActivityHandler :: Session 1346 reached intro marker.
tautulli  | 2023-06-09T17:09:10.822705851Z 2023-06-09 13:09:10 - ERROR :: CP Server Thread-11 : WebUI :: Mako template render error: (SystemError) AST constructor recursion depth mismatch (before=153, after=144) ("if False:pass\nelif data['media_type'] == 'episode'") in file '/app/tautulli/data/interfaces/default/current_activity_instance.html' at line: 455 char: 1
tautulli  | 2023-06-09T17:09:10.822778931Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:10.822793101Z   File "/app/tautulli/lib/mako/lookup.py", line 241, in get_template
tautulli  | 2023-06-09T17:09:10.822797871Z     return self._check(uri, self._collection[uri])
tautulli  | 2023-06-09T17:09:10.822802601Z                             ~~~~~~~~~~~~~~~~^^^^^
tautulli  | 2023-06-09T17:09:10.822806581Z KeyError: 'current_activity_instance.html'
tautulli  | 2023-06-09T17:09:10.822810551Z
tautulli  | 2023-06-09T17:09:10.822814491Z During handling of the above exception, another exception occurred:
tautulli  | 2023-06-09T17:09:10.822818801Z
tautulli  | 2023-06-09T17:09:10.822822611Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:10.822826540Z   File "/app/tautulli/lib/mako/pyparser.py", line 36, in parse
tautulli  | 2023-06-09T17:09:10.822830880Z     return _ast_util.parse(code, "<unknown>", mode)
tautulli  | 2023-06-09T17:09:10.822836000Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.822840070Z   File "/app/tautulli/lib/mako/_ast_util.py", line 91, in parse
tautulli  | 2023-06-09T17:09:10.822844340Z     return compile(expr, filename, mode, PyCF_ONLY_AST)
tautulli  | 2023-06-09T17:09:10.822850160Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.822891430Z SystemError: AST constructor recursion depth mismatch (before=153, after=144)
tautulli  | 2023-06-09T17:09:10.822895870Z
tautulli  | 2023-06-09T17:09:10.822899870Z The above exception was the direct cause of the following exception:
tautulli  | 2023-06-09T17:09:10.822903990Z
tautulli  | 2023-06-09T17:09:10.822908020Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:10.822911970Z   File "/app/tautulli/plexpy/webserve.py", line 136, in serve_template
tautulli  | 2023-06-09T17:09:10.822916270Z     template = _hplookup.get_template(templatename)
tautulli  | 2023-06-09T17:09:10.822920330Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.822924350Z   File "/app/tautulli/lib/mako/lookup.py", line 252, in get_template
tautulli  | 2023-06-09T17:09:10.822929360Z     return self._load(srcfile, uri)
tautulli  | 2023-06-09T17:09:10.822934030Z            ^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.822938230Z   File "/app/tautulli/lib/mako/lookup.py", line 313, in _load
tautulli  | 2023-06-09T17:09:10.822942720Z     self._collection[uri] = template = Template(
tautulli  | 2023-06-09T17:09:10.822946720Z                                        ^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.822950770Z   File "/app/tautulli/lib/mako/template.py", line 317, in __init__
tautulli  | 2023-06-09T17:09:10.822957330Z     module = self._compile_from_file(path, filename)
tautulli  | 2023-06-09T17:09:10.822964740Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.822968770Z   File "/app/tautulli/lib/mako/template.py", line 393, in _compile_from_file
tautulli  | 2023-06-09T17:09:10.822973040Z     code, module = _compile_text(self, data, filename)
tautulli  | 2023-06-09T17:09:10.822977060Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.822986700Z   File "/app/tautulli/lib/mako/template.py", line 677, in _compile_text
tautulli  | 2023-06-09T17:09:10.822991060Z     source, lexer = _compile(
tautulli  | 2023-06-09T17:09:10.822995030Z                     ^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.822998980Z   File "/app/tautulli/lib/mako/template.py", line 657, in _compile
tautulli  | 2023-06-09T17:09:10.823003200Z     node = lexer.parse()
tautulli  | 2023-06-09T17:09:10.823007130Z            ^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.823011100Z   File "/app/tautulli/lib/mako/lexer.py", line 240, in parse
tautulli  | 2023-06-09T17:09:10.823015240Z     if self.match_control_line():
tautulli  | 2023-06-09T17:09:10.823021290Z        ^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.823025310Z   File "/app/tautulli/lib/mako/lexer.py", line 457, in match_control_line
tautulli  | 2023-06-09T17:09:10.823030710Z     self.append_node(parsetree.ControlLine, keyword, isend, text)
tautulli  | 2023-06-09T17:09:10.823034939Z   File "/app/tautulli/lib/mako/lexer.py", line 129, in append_node
tautulli  | 2023-06-09T17:09:10.823039209Z     node = nodecls(*args, **kwargs)
tautulli  | 2023-06-09T17:09:10.823043529Z            ^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.823048339Z   File "/app/tautulli/lib/mako/parsetree.py", line 92, in __init__
tautulli  | 2023-06-09T17:09:10.823052579Z     code = ast.PythonFragment(text, **self.exception_kwargs)
tautulli  | 2023-06-09T17:09:10.823057059Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.823061459Z   File "/app/tautulli/lib/mako/ast.py", line 110, in __init__
tautulli  | 2023-06-09T17:09:10.823067049Z     super().__init__(code, **exception_kwargs)
tautulli  | 2023-06-09T17:09:10.823071019Z   File "/app/tautulli/lib/mako/ast.py", line 42, in __init__
tautulli  | 2023-06-09T17:09:10.823075439Z     expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
tautulli  | 2023-06-09T17:09:10.823079819Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:10.823084159Z   File "/app/tautulli/lib/mako/pyparser.py", line 38, in parse
tautulli  | 2023-06-09T17:09:10.823088439Z     raise exceptions.SyntaxException(
tautulli  | 2023-06-09T17:09:10.823092669Z mako.exceptions.SyntaxException: (SystemError) AST constructor recursion depth mismatch (before=153, after=144) ("if False:pass\nelif data['media_type'] == 'episode'") in file '/app/tautulli/data/interfaces/default/current_activity_instance.html' at line: 455 char: 1
tautulli  | 2023-06-09T17:09:11.287913815Z 2023-06-09 13:09:11 - ERROR :: CP Server Thread-5 : WebUI :: Mako template render error: (SystemError) AST constructor recursion depth mismatch (before=150, after=146) ("page('pms_image_proxy', data['thumb'], data['ratin") in file '/app/tautulli/data/interfaces/default/current_activity_instance.html' at line: 125 char: 111
tautulli  | 2023-06-09T17:09:11.287939605Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:11.287945355Z   File "/app/tautulli/lib/mako/lookup.py", line 241, in get_template
tautulli  | 2023-06-09T17:09:11.287949965Z     return self._check(uri, self._collection[uri])
tautulli  | 2023-06-09T17:09:11.287962035Z                             ~~~~~~~~~~~~~~~~^^^^^
tautulli  | 2023-06-09T17:09:11.287966305Z KeyError: 'current_activity_instance.html'
tautulli  | 2023-06-09T17:09:11.287970725Z
tautulli  | 2023-06-09T17:09:11.287975035Z During handling of the above exception, another exception occurred:
tautulli  | 2023-06-09T17:09:11.287979284Z
tautulli  | 2023-06-09T17:09:11.287983184Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:11.287987444Z   File "/app/tautulli/lib/mako/pyparser.py", line 36, in parse
tautulli  | 2023-06-09T17:09:11.288029594Z     return _ast_util.parse(code, "<unknown>", mode)
tautulli  | 2023-06-09T17:09:11.288034614Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288038784Z   File "/app/tautulli/lib/mako/_ast_util.py", line 91, in parse
tautulli  | 2023-06-09T17:09:11.288043104Z     return compile(expr, filename, mode, PyCF_ONLY_AST)
tautulli  | 2023-06-09T17:09:11.288047124Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288051164Z SystemError: AST constructor recursion depth mismatch (before=150, after=146)
tautulli  | 2023-06-09T17:09:11.288055344Z
tautulli  | 2023-06-09T17:09:11.288059124Z The above exception was the direct cause of the following exception:
tautulli  | 2023-06-09T17:09:11.288063214Z
tautulli  | 2023-06-09T17:09:11.288067014Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:11.288071004Z   File "/app/tautulli/plexpy/webserve.py", line 136, in serve_template
tautulli  | 2023-06-09T17:09:11.288075304Z     template = _hplookup.get_template(templatename)
tautulli  | 2023-06-09T17:09:11.288079404Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288083404Z   File "/app/tautulli/lib/mako/lookup.py", line 252, in get_template
tautulli  | 2023-06-09T17:09:11.288090644Z     return self._load(srcfile, uri)
tautulli  | 2023-06-09T17:09:11.288096184Z            ^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288100124Z   File "/app/tautulli/lib/mako/lookup.py", line 313, in _load
tautulli  | 2023-06-09T17:09:11.288104264Z     self._collection[uri] = template = Template(
tautulli  | 2023-06-09T17:09:11.288108254Z                                        ^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288112444Z   File "/app/tautulli/lib/mako/template.py", line 317, in __init__
tautulli  | 2023-06-09T17:09:11.288116804Z     module = self._compile_from_file(path, filename)
tautulli  | 2023-06-09T17:09:11.288120804Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288125304Z   File "/app/tautulli/lib/mako/template.py", line 393, in _compile_from_file
tautulli  | 2023-06-09T17:09:11.288129514Z     code, module = _compile_text(self, data, filename)
tautulli  | 2023-06-09T17:09:11.288133554Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288138684Z   File "/app/tautulli/lib/mako/template.py", line 677, in _compile_text
tautulli  | 2023-06-09T17:09:11.288142994Z     source, lexer = _compile(
tautulli  | 2023-06-09T17:09:11.288147344Z                     ^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288154914Z   File "/app/tautulli/lib/mako/template.py", line 657, in _compile
tautulli  | 2023-06-09T17:09:11.288159204Z     node = lexer.parse()
tautulli  | 2023-06-09T17:09:11.288163114Z            ^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288167034Z   File "/app/tautulli/lib/mako/lexer.py", line 238, in parse
tautulli  | 2023-06-09T17:09:11.288171944Z     if self.match_expression():
tautulli  | 2023-06-09T17:09:11.288175864Z        ^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288179894Z   File "/app/tautulli/lib/mako/lexer.py", line 415, in match_expression
tautulli  | 2023-06-09T17:09:11.288184264Z     self.append_node(
tautulli  | 2023-06-09T17:09:11.288188164Z   File "/app/tautulli/lib/mako/lexer.py", line 129, in append_node
tautulli  | 2023-06-09T17:09:11.288193563Z     node = nodecls(*args, **kwargs)
tautulli  | 2023-06-09T17:09:11.288197523Z            ^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288201473Z   File "/app/tautulli/lib/mako/parsetree.py", line 201, in __init__
tautulli  | 2023-06-09T17:09:11.288205763Z     self.code = ast.PythonCode(text, **self.exception_kwargs)
tautulli  | 2023-06-09T17:09:11.288209813Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288213823Z   File "/app/tautulli/lib/mako/ast.py", line 42, in __init__
tautulli  | 2023-06-09T17:09:11.288218303Z     expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
tautulli  | 2023-06-09T17:09:11.288223303Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.288228523Z   File "/app/tautulli/lib/mako/pyparser.py", line 38, in parse
tautulli  | 2023-06-09T17:09:11.288233033Z     raise exceptions.SyntaxException(
tautulli  | 2023-06-09T17:09:11.288237123Z mako.exceptions.SyntaxException: (SystemError) AST constructor recursion depth mismatch (before=150, after=146) ("page('pms_image_proxy', data['thumb'], data['ratin") in file '/app/tautulli/data/interfaces/default/current_activity_instance.html' at line: 125 char: 111
tautulli  | 2023-06-09T17:09:11.380430110Z 2023-06-09 13:09:11 - ERROR :: CP Server Thread-13 : WebUI :: Mako template render error: (SystemError) AST constructor recursion depth mismatch (before=153, after=126) ("if False:pass\nelif data['media_type'] == 'episode'") in file '/app/tautulli/data/interfaces/default/current_activity_instance.html' at line: 491 char: 1
tautulli  | 2023-06-09T17:09:11.380496320Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:11.380502770Z   File "/app/tautulli/lib/mako/lookup.py", line 241, in get_template
tautulli  | 2023-06-09T17:09:11.380507470Z     return self._check(uri, self._collection[uri])
tautulli  | 2023-06-09T17:09:11.380511540Z                             ~~~~~~~~~~~~~~~~^^^^^
tautulli  | 2023-06-09T17:09:11.380515530Z KeyError: 'current_activity_instance.html'
tautulli  | 2023-06-09T17:09:11.380519580Z
tautulli  | 2023-06-09T17:09:11.380523460Z During handling of the above exception, another exception occurred:
tautulli  | 2023-06-09T17:09:11.380527590Z
tautulli  | 2023-06-09T17:09:11.380531400Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:11.380547609Z   File "/app/tautulli/lib/mako/pyparser.py", line 36, in parse
tautulli  | 2023-06-09T17:09:11.380552189Z     return _ast_util.parse(code, "<unknown>", mode)
tautulli  | 2023-06-09T17:09:11.380557229Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380571269Z   File "/app/tautulli/lib/mako/_ast_util.py", line 91, in parse
tautulli  | 2023-06-09T17:09:11.380575449Z     return compile(expr, filename, mode, PyCF_ONLY_AST)
tautulli  | 2023-06-09T17:09:11.380579719Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380584169Z SystemError: AST constructor recursion depth mismatch (before=153, after=126)
tautulli  | 2023-06-09T17:09:11.380588729Z
tautulli  | 2023-06-09T17:09:11.380592689Z The above exception was the direct cause of the following exception:
tautulli  | 2023-06-09T17:09:11.380596789Z
tautulli  | 2023-06-09T17:09:11.380600579Z Traceback (most recent call last):
tautulli  | 2023-06-09T17:09:11.380604489Z   File "/app/tautulli/plexpy/webserve.py", line 136, in serve_template
tautulli  | 2023-06-09T17:09:11.380608679Z     template = _hplookup.get_template(templatename)
tautulli  | 2023-06-09T17:09:11.380612669Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380616659Z   File "/app/tautulli/lib/mako/lookup.py", line 252, in get_template
tautulli  | 2023-06-09T17:09:11.380620799Z     return self._load(srcfile, uri)
tautulli  | 2023-06-09T17:09:11.380624809Z            ^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380628739Z   File "/app/tautulli/lib/mako/lookup.py", line 313, in _load
tautulli  | 2023-06-09T17:09:11.380633219Z     self._collection[uri] = template = Template(
tautulli  | 2023-06-09T17:09:11.380638149Z                                        ^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380642109Z   File "/app/tautulli/lib/mako/template.py", line 317, in __init__
tautulli  | 2023-06-09T17:09:11.380646279Z     module = self._compile_from_file(path, filename)
tautulli  | 2023-06-09T17:09:11.380650379Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380654339Z   File "/app/tautulli/lib/mako/template.py", line 393, in _compile_from_file
tautulli  | 2023-06-09T17:09:11.380658659Z     code, module = _compile_text(self, data, filename)
tautulli  | 2023-06-09T17:09:11.380664659Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380670459Z   File "/app/tautulli/lib/mako/template.py", line 677, in _compile_text
tautulli  | 2023-06-09T17:09:11.380674889Z     source, lexer = _compile(
tautulli  | 2023-06-09T17:09:11.380678819Z                     ^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380682779Z   File "/app/tautulli/lib/mako/template.py", line 657, in _compile
tautulli  | 2023-06-09T17:09:11.380686909Z     node = lexer.parse()
tautulli  | 2023-06-09T17:09:11.380690799Z            ^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380695029Z   File "/app/tautulli/lib/mako/lexer.py", line 240, in parse
tautulli  | 2023-06-09T17:09:11.380699119Z     if self.match_control_line():
tautulli  | 2023-06-09T17:09:11.380706569Z        ^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380710669Z   File "/app/tautulli/lib/mako/lexer.py", line 457, in match_control_line
tautulli  | 2023-06-09T17:09:11.380714819Z     self.append_node(parsetree.ControlLine, keyword, isend, text)
tautulli  | 2023-06-09T17:09:11.380718949Z   File "/app/tautulli/lib/mako/lexer.py", line 129, in append_node
tautulli  | 2023-06-09T17:09:11.380723059Z     node = nodecls(*args, **kwargs)
tautulli  | 2023-06-09T17:09:11.380727149Z            ^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380732109Z   File "/app/tautulli/lib/mako/parsetree.py", line 92, in __init__
tautulli  | 2023-06-09T17:09:11.380736769Z     code = ast.PythonFragment(text, **self.exception_kwargs)
tautulli  | 2023-06-09T17:09:11.380741499Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380745659Z   File "/app/tautulli/lib/mako/ast.py", line 110, in __init__
tautulli  | 2023-06-09T17:09:11.380750009Z     super().__init__(code, **exception_kwargs)
tautulli  | 2023-06-09T17:09:11.380753948Z   File "/app/tautulli/lib/mako/ast.py", line 42, in __init__
tautulli  | 2023-06-09T17:09:11.380758038Z     expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
tautulli  | 2023-06-09T17:09:11.380762218Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tautulli  | 2023-06-09T17:09:11.380766708Z   File "/app/tautulli/lib/mako/pyparser.py", line 38, in parse
tautulli  | 2023-06-09T17:09:11.380771238Z     raise exceptions.SyntaxException(
tautulli  | 2023-06-09T17:09:11.380778668Z mako.exceptions.SyntaxException: (SystemError) AST constructor recursion depth mismatch (before=153, after=126) ("if False:pass\nelif data['media_type'] == 'episode'") in file '/app/tautulli/data/interfaces/default/current_activity_instance.html' at line: 491 char: 1
tautulli  | 2023-06-09T17:09:20.436215987Z 2023-06-09 13:09:20 - ERROR :: CP Server Thread-6 : WebUI :: Mako template render error: (SystemError) AST constructor recursion depth mismatch (before=150, after=146) ("if data['live']:\n    background_url = page('pms_im") in file '/app/tautulli/data/interfaces/default/current_activity_instance.html' at line: 83 char: 9
```

**Comment by darthShadow** [comment]
Looks like alpine 3.15 has python 3.9 and the corresponding base image still seems to be maintained. Would it be possible to downgrade to that?

**Comment by xconverge** [comment]
I opted to just use the official image instead of linuxserver's for now due to this, no issues now
