### ISSUE TITLE
Plexpy doesn't work since last week

### ISSUE THREAD

**Issue by elmero1** [linuxserver/docker-tautulli#37]
Since approximately one week my plexpy doesn't work. The container is started but i can't reach plexpy with the webbrowser. 
Here is a docker logs output:

> Unable to create the log directory. Logging to screen only.
Traceback (most recent call last):
  File "/app/plexpy/PlexPy.py", line 260, in <module>
    main()
  File "/app/plexpy/PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
  File "/app/plexpy/plexpy/__init__.py", line 129, in initialize
    verbose=VERBOSE)
  File "/app/plexpy/plexpy/logger.py", line 205, in initLogger
    file_handler = handlers.RotatingFileHandler(filename, maxBytes=MAX_SIZE, backupCount=MAX_FILES)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/run/s6/services/plexpy/None/plexpy.log'

Below my ls and docker-compose output:

> root@OMV01:/opt/plexpy#ls -ln
total 20K
drwxr-xr-x 3 dockeradm dockergrp 4.0K Jul 31 10:52 .
drwxr-xr-x 8 root      root      4.0K Jul 31 10:45 ..
drwxr-xr-x 5 dockeradm dockergrp 4.0K Jul 31 10:10 data
-rwxr-xr-x 1 dockeradm dockergrp  284 Jul 31 10:52 docker-compose.yml
lrwxrwxrwx 1 dockeradm dockergrp  106 Jul 31 10:50 plexlogs -> /media/9c5fd0e3-1d4c-45d7-88a7-ffbfbe786174/plexmediaserver/Library/Application Support/Plex Media Server/

> version: '2'
services:
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    restart: always
    ports:
      - 8181:8181
    volumes:
      - /opt/plexpy/data:/config
      - /opt/plexpy/plexlogs/Logs:/logs:ro
    environment:
      - PUID=1001
      - PGID=1000

**Comment by grantbevis** [comment]
Same issue here, have recreated the container and pulled the latest image and still no luck

```
Unable to create the log directory. Logging to screen only.
Traceback (most recent call last):
  File "/app/plexpy/PlexPy.py", line 260, in <module>
    main()
  File "/app/plexpy/PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
  File "/app/plexpy/plexpy/__init__.py", line 129, in initialize
    verbose=VERBOSE)
  File "/app/plexpy/plexpy/logger.py", line 205, in initLogger
    file_handler = handlers.RotatingFileHandler(filename, maxBytes=MAX_SIZE, backupCount=MAX_FILES)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/run/s6/services/plexpy/None/plexpy.log'
```

**Comment by sparklyballs** [comment]
the fix appears to be editing the config.ini file in your /config mount and checking/changing the entries for 

`log_dir = /config/logs`
`backup_dir = /config/backups`
`cache_dir = /config/cache`

**Comment by elmero1** [comment]
Thank you sparklyballs. Now it works!

**Comment by sparklyballs** [comment]
cool

gonna close this

**Comment by jmlw** [comment]
This took a long time to find, can this also be included as additional info or caveats in documentation?
