### ISSUE TITLE
Mounting cifs automount volume for /config fails on startup

### ISSUE THREAD

**Issue by alexholliz** [linuxserver/docker-tautulli#55]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: Ubuntu 16.04

Docker-Compose settings:
```
version: '2'
services:
  tautulli:
    image: linuxserver/tautulli
    environment:
      TZ: America/Chicago
    stdin_open: true
    volumes:
    - /Volumes/Shares/configs/tautulli:/config
    tty: true
    ports:
    - 8181:8181/tcp
    labels:
      io.rancher.container.pull_image: always
```
Log Output
```
5/18/2018 8:57:47 PM[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
5/18/2018 8:57:47 PM[s6-init] ensuring user provided files have correct perms...exited 0.
5/18/2018 8:57:47 PM[fix-attrs.d] applying ownership & permissions fixes...
5/18/2018 8:57:47 PM[fix-attrs.d] done.
5/18/2018 8:57:47 PM[cont-init.d] executing container initialization scripts...
5/18/2018 8:57:47 PM[cont-init.d] 10-adduser: executing...
5/18/2018 8:57:48 PMusermod: no changes
5/18/2018 8:57:48 PM
5/18/2018 8:57:48 PM-------------------------------------
5/18/2018 8:57:48 PM          _         ()
5/18/2018 8:57:48 PM         | |  ___   _    __
5/18/2018 8:57:48 PM         | | / __| | |  /  \
5/18/2018 8:57:48 PM         | | \__ \ | | | () |
5/18/2018 8:57:48 PM         |_| |___/ |_|  \__/
5/18/2018 8:57:48 PM
5/18/2018 8:57:48 PM
5/18/2018 8:57:48 PMBrought to you by linuxserver.io
5/18/2018 8:57:48 PMWe gratefully accept donations at:
5/18/2018 8:57:48 PMhttps://www.linuxserver.io/donations/
5/18/2018 8:57:48 PM-------------------------------------
5/18/2018 8:57:48 PMGID/UID
5/18/2018 8:57:48 PM-------------------------------------
5/18/2018 8:57:48 PM
5/18/2018 8:57:48 PMUser uid:    911
5/18/2018 8:57:48 PMUser gid:    911
5/18/2018 8:57:48 PM-------------------------------------
5/18/2018 8:57:48 PM
5/18/2018 8:57:48 PM[cont-init.d] 10-adduser: exited 0.
5/18/2018 8:57:48 PM[cont-init.d] 30-config: executing...
5/18/2018 8:59:49 PM[cont-init.d] 30-config: exited 0.
5/18/2018 8:59:49 PM[cont-init.d] done.
5/18/2018 8:59:49 PM[services.d] starting services
5/18/2018 8:59:49 PM[services.d] done.
5/18/2018 8:59:51 PM2018-05-18 20:59:51 - INFO :: MainThread : Checking if the database upgrades are required...
5/18/2018 8:59:56 PM2018-05-18 20:59:56 - ERROR :: MainThread : Can't connect to the database: database is locked
5/18/2018 8:59:56 PM2018-05-18 20:59:56 - INFO :: MainThread : Checking if configuration upgrades are required...
5/18/2018 8:59:56 PM2018-05-18 20:59:56 - INFO :: MainThread : Tautulli Notifiers :: Upgrading to new notification system...
5/18/2018 8:59:56 PM2018-05-18 20:59:56 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
5/18/2018 8:59:56 PM2018-05-18 20:59:56 - INFO :: MainThread : Tautulli Libraries :: Upgrading library notification toggles...
5/18/2018 8:59:56 PM2018-05-18 20:59:56 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
5/18/2018 9:00:16 PM2018-05-18 21:00:16 - ERROR :: MainThread : Could not perform upgrades: database is locked
5/18/2018 9:00:36 PM2018-05-18 21:00:36 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
5/18/2018 9:00:36 PM  File "/app/tautulli/PlexPy.py", line 28, in <module>
5/18/2018 9:00:36 PM    main()
5/18/2018 9:00:36 PM  File "/app/tautulli/Tautulli.py", line 200, in main
5/18/2018 9:00:36 PM    plexpy.initialize(config_file)
5/18/2018 9:00:36 PM  File "/app/tautulli/plexpy/__init__.py", line 194, in initialize
5/18/2018 9:00:36 PM    notifiers.blacklist_logger()
5/18/2018 9:00:36 PM  File "/app/tautulli/plexpy/notifiers.py", line 612, in blacklist_logger
5/18/2018 9:00:36 PM    db = database.MonitorDatabase()
5/18/2018 9:00:36 PM  File "/app/tautulli/plexpy/database.py", line 125, in __init__
5/18/2018 9:00:36 PM    self.connection.execute("PRAGMA journal_mode = %s" % plexpy.CONFIG.JOURNAL_MODE)
5/18/2018 9:00:36 PMOperationalError: database is locked
5/18/2018 9:00:36 PM
5/18/2018 9:00:36 PMTraceback (most recent call last):
5/18/2018 9:00:36 PM  File "/app/tautulli/PlexPy.py", line 28, in <module>
5/18/2018 9:00:36 PM    main()
5/18/2018 9:00:36 PM  File "/app/tautulli/Tautulli.py", line 200, in main
5/18/2018 9:00:36 PM    plexpy.initialize(config_file)
5/18/2018 9:00:36 PM  File "/app/tautulli/plexpy/__init__.py", line 194, in initialize
5/18/2018 9:00:36 PM    notifiers.blacklist_logger()
5/18/2018 9:00:36 PM  File "/app/tautulli/plexpy/notifiers.py", line 612, in blacklist_logger
5/18/2018 9:00:36 PM    db = database.MonitorDatabase()
5/18/2018 9:00:36 PM  File "/app/tautulli/plexpy/database.py", line 125, in __init__
5/18/2018 9:00:36 PM    self.connection.execute("PRAGMA journal_mode = %s" % plexpy.CONFIG.JOURNAL_MODE)
5/18/2018 9:00:36 PMsqlite3.OperationalError: database is locked
5/18/2018 9:00:37 PM2018-05-18 21:00:37 - INFO :: MainThread : Checking if the database upgrades are required...
5/18/2018 9:00:42 PM2018-05-18 21:00:42 - ERROR :: MainThread : Can't connect to the database: database is locked
5/18/2018 9:00:42 PM2018-05-18 21:00:42 - INFO :: MainThread : Checking if configuration upgrades are required...
5/18/2018 9:01:02 PM2018-05-18 21:01:02 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
5/18/2018 9:01:02 PM  File "/app/tautulli/PlexPy.py", line 28, in <module>
5/18/2018 9:01:02 PM    main()
5/18/2018 9:01:02 PM  File "/app/tautulli/Tautulli.py", line 200, in main
5/18/2018 9:01:02 PM    plexpy.initialize(config_file)
5/18/2018 9:01:02 PM  File "/app/tautulli/plexpy/__init__.py", line 194, in initialize
5/18/2018 9:01:02 PM    notifiers.blacklist_logger()
5/18/2018 9:01:02 PM  File "/app/tautulli/plexpy/notifiers.py", line 612, in blacklist_logger
5/18/2018 9:01:02 PM    db = database.MonitorDatabase()
5/18/2018 9:01:02 PM  File "/app/tautulli/plexpy/database.py", line 125, in __init__
5/18/2018 9:01:02 PM    self.connection.execute("PRAGMA journal_mode = %s" % plexpy.CONFIG.JOURNAL_MODE)
5/18/2018 9:01:02 PMOperationalError: database is locked
5/18/2018 9:01:02 PM
5/18/2018 9:01:02 PMTraceback (most recent call last):
5/18/2018 9:01:02 PM  File "/app/tautulli/PlexPy.py", line 28, in <module>
5/18/2018 9:01:02 PM    main()
5/18/2018 9:01:02 PM  File "/app/tautulli/Tautulli.py", line 200, in main
5/18/2018 9:01:02 PM    plexpy.initialize(config_file)
5/18/2018 9:01:02 PM  File "/app/tautulli/plexpy/__init__.py", line 194, in initialize
5/18/2018 9:01:02 PM    notifiers.blacklist_logger()
5/18/2018 9:01:02 PM  File "/app/tautulli/plexpy/notifiers.py", line 612, in blacklist_logger
5/18/2018 9:01:02 PM    db = database.MonitorDatabase()
5/18/2018 9:01:02 PM  File "/app/tautulli/plexpy/database.py", line 125, in __init__
5/18/2018 9:01:02 PM    self.connection.execute("PRAGMA journal_mode = %s" % plexpy.CONFIG.JOURNAL_MODE)
5/18/2018 9:01:02 PMsqlite3.OperationalError: database is locked
5/18/2018 9:01:02 PM2018-05-18 21:01:02 - INFO :: MainThread : Checking if the database upgrades are required...
5/18/2018 9:01:07 PM2018-05-18 21:01:07 - ERROR :: MainThread : Can't connect to the database: database is locked
5/18/2018 9:01:07 PM2018-05-18 21:01:07 - INFO :: MainThread : Checking if configuration upgrades are required...
5/18/2018 9:01:28 PM2018-05-18 21:01:28 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
5/18/2018 9:01:28 PM  File "/app/tautulli/PlexPy.py", line 28, in <module>
5/18/2018 9:01:28 PM    main()
5/18/2018 9:01:28 PM  File "/app/tautulli/Tautulli.py", line 200, in main
5/18/2018 9:01:28 PM    plexpy.initialize(config_file)
5/18/2018 9:01:28 PM  File "/app/tautulli/plexpy/__init__.py", line 194, in initialize
5/18/2018 9:01:28 PM    notifiers.blacklist_logger()
5/18/2018 9:01:28 PM  File "/app/tautulli/plexpy/notifiers.py", line 612, in blacklist_logger
5/18/2018 9:01:28 PM    db = database.MonitorDatabase()
5/18/2018 9:01:28 PM  File "/app/tautulli/plexpy/database.py", line 125, in __init__
5/18/2018 9:01:28 PM    self.connection.execute("PRAGMA journal_mode = %s" % plexpy.CONFIG.JOURNAL_MODE)
5/18/2018 9:01:28 PMOperationalError: database is locked
5/18/2018 9:01:28 PM
5/18/2018 9:01:28 PMTraceback (most recent call last):
5/18/2018 9:01:28 PM  File "/app/tautulli/PlexPy.py", line 28, in <module>
5/18/2018 9:01:28 PM    main()
5/18/2018 9:01:28 PM  File "/app/tautulli/Tautulli.py", line 200, in main
5/18/2018 9:01:28 PM    plexpy.initialize(config_file)
5/18/2018 9:01:28 PM  File "/app/tautulli/plexpy/__init__.py", line 194, in initialize
5/18/2018 9:01:28 PM    notifiers.blacklist_logger()
5/18/2018 9:01:28 PM  File "/app/tautulli/plexpy/notifiers.py", line 612, in blacklist_logger
5/18/2018 9:01:28 PM    db = database.MonitorDatabase()
5/18/2018 9:01:28 PM  File "/app/tautulli/plexpy/database.py", line 125, in __init__
5/18/2018 9:01:28 PM    self.connection.execute("PRAGMA journal_mode = %s" % plexpy.CONFIG.JOURNAL_MODE)
5/18/2018 9:01:28 PMsqlite3.OperationalError: database is locked
5/18/2018 9:01:28 PM2018-05-18 21:01:28 - INFO :: MainThread : Checking if the database upgrades are required...
5/18/2018 9:01:33 PM2018-05-18 21:01:33 - ERROR :: MainThread : Can't connect to the database: database is locked
5/18/2018 9:01:33 PM2018-05-18 21:01:33 - INFO :: MainThread : Checking if configuration upgrades are required...
```

Automount setup:
* My docker host is setup to use autofs to mount a cifs share on my network to /Volumes/Shares/
* The Docker compose file mounts /Volumes/Shares/configs/tautulli to /config inside the docker host
* This works just fine for linuxserver/sonarr and radarr, so I'm at a loss for why there'd be permissions issues here
* The config directory is written to (checked via docker shell on the host and on the cifs share itself), but then the logs show that tautulli is complaining about the database being locked

**Comment by alexholliz** [comment]
Confirmed that the `MainThread : Can't connect to the database: database is locked` error occurs even when the config directory has been wiped out, and the PGID and PUID are set to root (0)

**Comment by aptalca** [comment]
Sqlite does not play well with mounted shares.

We recommend putting the config folders on a local path. Media folders can be on mounted shares.

**Comment by alexholliz** [comment]
Well, that's a bummer, is there any way to get the config persistent among reboots? Should I just use a local disk and back it up?

**Comment by j0nnymoe** [comment]
Correct :)

**Comment by alexholliz** [comment]
Oof, more research into sqlite and docker proves this out. I'll look into using an external DB for tautalli. I'll get those issues into the correct repo. Thanks for your help folks. :)

**Comment by jlhunter2008** [comment]
I got the database is locked error on my Synology. What steps do I need to take to remedy this? Detailed instructions would be appreciated.

Thanks.
